services:
  postgres:
    image: postgres:15-alpine
    container_name: launchpad-postgres
    environment:
      POSTGRES_DB: launchpad
      POSTGRES_USER: launchpad
      POSTGRES_PASSWORD: launchpad123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U launchpad -d launchpad"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: launchpad-api
    environment:
      PORT: 3001
      ENVIRONMENT: development
      DATABASE_URL: postgres://launchpad:launchpad123@postgres:5432/launchpad?sslmode=disable
      JWT_SECRET: your-super-secret-jwt-key-that-should-be-at-least-32-characters-long
      JWT_EXPIRATION_HOURS: 24
      GITHUB_CLIENT_ID: your-github-client-id
      GITHUB_CLIENT_SECRET: your-github-client-secret
      MAX_FILE_UPLOAD_SIZE: 10485760
      REQUEST_TIMEOUT_SECONDS: 60
      DEFAULT_PAGE_SIZE: 20
      MAX_PAGE_SIZE: 100
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
