apiVersion: apps/v1
kind: Deployment
metadata:
  name: launchpad
spec:
  template:
    spec:
      containers:
      - name: launchpad
        # Production-like resources for staging
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        # Staging environment variables
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "info"
