name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'dev'

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - { name: prod,  file: Dockerfile,      build-args: "" }
          - { name: dev,   file: Dockerfile,      build-args: "" }

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/launchpad-${{ matrix.image.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push ${{ matrix.image.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image.file }}
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ matrix.image.build-args }}
