// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package email

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AuthCodeEmail(code string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Email Verification Code</title></head><body style=\"margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, &#39;Segoe UI&#39;, Roboto, &#39;Helvetica Neue&#39;, Arial, sans-serif;\"><table role=\"presentation\" style=\"width: 100%; border-collapse: collapse;\"><tr><td align=\"center\" style=\"padding: 40px 0;\"><table role=\"presentation\" style=\"width: 600px; border-collapse: collapse; background-color: #ffffff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);\"><!-- Header --><tr><td style=\"padding: 40px 40px 20px 40px; text-align: center;\"><h1 style=\"margin: 0; color: #1a1a1a; font-size: 28px; font-weight: 600;\">Verify Your Email</h1></td></tr><!-- Body --><tr><td style=\"padding: 20px 40px;\"><p style=\"margin: 0 0 20px 0; color: #4a5568; font-size: 16px; line-height: 1.5;\">Thank you for signing up! Please use the verification code below to complete your registration:</p><!-- Verification Code --><table role=\"presentation\" style=\"width: 100%; border-collapse: collapse; margin: 30px 0;\"><tr><td align=\"center\" style=\"padding: 20px; background-color: #f7fafc; border-radius: 8px;\"><div style=\"font-size: 36px; font-weight: 700; letter-spacing: 8px; color: #2d3748; font-family: &#39;Courier New&#39;, monospace;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(code)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/email/auth_code.templ`, Line: 33, Col: 19}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></td></tr></table><p style=\"margin: 20px 0 0 0; color: #4a5568; font-size: 16px; line-height: 1.5;\">This code will expire in <strong>10 minutes</strong>.</p><p style=\"margin: 20px 0 0 0; color: #718096; font-size: 14px; line-height: 1.5;\">If you didn't request this code, you can safely ignore this email.</p></td></tr><!-- Footer --><tr><td style=\"padding: 30px 40px; border-top: 1px solid #e2e8f0;\"><p style=\"margin: 0; color: #a0aec0; font-size: 12px; text-align: center;\">This is an automated message from Launchpad. Please do not reply to this email.</p></td></tr></table></td></tr></table></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
